version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9393:9393"
    environment:
      - CSVSERVER_BORDER=Orange
    volumes:
      - ./inputFile:/inputFile
