version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9393:9393"
    environment:
      - CSVSERVER_BORDER=Orange
    volumes:
      - ./inputFile:/inputFile
    metrics:
      path: /metrics
      port: 9393

  prometheus:
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
